name: Deepfake Detector CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn tensorflow pillow requests

    - name: Download model from GitHub
      run: |
        wget https://raw.githubusercontent.com/<username>/<repo>/<branch>/path/to/your_model.h5 -O projectthingy.h5

    - name: Run application
      run: uvicorn main:app --host 0.0.0.0 --port 8000
